### PR TITLE
Convert blog/news into reports

### PR DESCRIPTION
**Pull request by zupo**
Also move past events into a separate directory.

Work-In-Progress, don't merge yet.

### CODE REVIEW

**Comment by zupo** [comment]
@domenkozar: ready for review

**Comment by domenkozar** [comment]
Let's put blog posts at the end, as in "more" section and make them links?

**Comment by zupo** [comment]
I don't understand what you are trying to say. I removed the blog. And Reports are the send to last item in the nav bar.

**Comment by zupo** [comment]
Ah, I get it. 

Yeah I agree.

**Pull request merged**
